# Generated by Django 5.2.5 on 2025-11-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_mobile_specifications_mobile_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='specifications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
