# Generated by Django 5.2.5 on 2025-11-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_mobile_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='specifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
