# Generated by Django 5.2.5 on 2025-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_mobile_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='review1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='review2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='review3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='review4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='review5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer1_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer2_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer3_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer4_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer5_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
    ]
