# Generated by Django 5.2.5 on 2025-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_mobile_review1_mobile_review2_mobile_review3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='review6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='reviewer6_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
    ]
