# Generated by Django 5.2.5 on 2025-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mobile_review6_mobile_reviewer6_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphones',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='review6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer1_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer2_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer3_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer4_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer5_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='reviewer6_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='headphones',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='review6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer1_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer2_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer3_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer4_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer5_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='reviewer6_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='review6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer1_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer2_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer3_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer4_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer5_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='reviewer6_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='camera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='review6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer1_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer2_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer3_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer4_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer5_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='reviewer6_profile',
            field=models.ImageField(blank=True, null=True, upload_to='reviewers/'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='image',
            field=models.ImageField(upload_to='mobiles/'),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='specifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='mobiles/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='specifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='image',
            field=models.ImageField(upload_to='mobiles/'),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='specifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='image',
            field=models.ImageField(upload_to='mobiles/'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='specifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
