# Generated by Django 5.2.5 on 2026-01-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_headphones_battery_headphones_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headphones',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='display',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='storage',
        ),
    ]
